install! 'cocoapods', :warn_for_unused_master_specs_repo => false
use_frameworks!

platform :ios, '9.0'

target 'MNSwiftKit_Example' do

  #pod 'MNSwiftKit', :path => '../'
  #pod 'MNSwiftKit/UI', :path => '../'
  #pod 'MNSwiftKit/Unity', :path => '../'
  #pod 'MNSwiftKit/Toast', :path => '../'
  #pod 'MNSwiftKit/Player', :path => '../'
  #pod 'MNSwiftKit/Spliter', :path => '../'
  #pod 'MNSwiftKit/Layout', :path => '../'
  pod 'MNSwiftKit/Activity', :path => '../'
  #pod 'MNSwiftKit/Refresh', :path => '../'
  #pod 'MNSwiftKit/Exporter', :path => '../'
  #pod 'MNSwiftKit/Purchase', :path => '../'
  #pod 'MNSwiftKit/Database', :path => '../'
  #pod 'MNSwiftKit/Definition', :path => '../'
  #pod 'MNSwiftKit/Extension', :path => '../'
  #pod 'MNSwiftKit/Controller', :path => '../'
  #pod 'MNSwiftKit/EmptyView', :path => '../'
  #pod 'MNSwiftKit/Networking', :path => '../'
  #pod 'MNSwiftKit/Transitioning', :path => '../'
  #pod 'MNSwiftKit/HTTPRequest', :path => '../'
  
  target 'MNSwiftKit_Tests' do
    inherit! :search_paths
    
  end
end
