name: build

defaults:
  run:
    shell: bash -leo pipefail {0}

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Swift Package
        run: |
          xcodebuild build \
            -scheme MNSwiftKit \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.5,arch=arm64' \
            -configuration Debug \
            -quiet

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: Example/Pods
          key: pods-${{ hashFiles('Example/Podfile.lock') }}
          restore-keys: |
            pods-

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Pod Install
        working-directory: Example
        run: pod install

      - name: Build Example
        run: |
          xcodebuild build-for-testing \
            -workspace Example/MNSwiftKit_Example.xcworkspace \
            -scheme MNSwiftKit_Example \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro Max,OS=18.5,arch=arm64' \
            -configuration Debug \
            CODE_SIGNING_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -quiet

      - name: Run Tests
        run: |
          xcodebuild test-without-building \
            -workspace Example/MNSwiftKit_Example.xcworkspace \
            -scheme MNSwiftKit_Example \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
            -configuration Debug \
            -only-testing:MNSwiftKit_Tests \
            CODE_SIGNING_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      - name: Pod Lib Lint
        run: pod lib lint MNSwiftKit.podspec --allow-warnings
